# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4db5cd4d234926c884c83e3be31e80da3c5450aa9390c3fd85eff8ca3a6bc5343339bced8c55d3d45d50b7cb7244e0d415123e806820a6ab91dbc2646f0ba55

test:
  secret_key_base: 237f6672e57ae0e2127efa7b7b4930864054ef2c473095d1f91f9aae4adf16e64087bfe775d50203c6eadf54dbc7b6b91e0501c5a12cdfbd71489c7c9cf2c6a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
